/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing.Gerant;

import Metiers.GestionClients;
import TableModele.MonModele;
import java.sql.ResultSet;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;

/**
 *
 * @author acer
 */
public class JPClient extends javax.swing.JPanel {
       GestionClients Gc = new GestionClients();
        IHMGerant Jp;
         boolean reserver = false ;
   
    public JPClient() {
        initComponents();
    }
    
    public JPClient(IHMGerant Jp)
    {
        this.Jp=Jp ;
        initComponents();
        AfficherReservation();
        Filtrer();
        
    }
    
     public void AfficherReservation()
    {
       
        ResultSet Res = Gc.Client_Actuel();
        MonModele modele = new MonModele(Res);
        Tclient.setModel(modele);
    }

     public void Filtrer()
    {
       nomtext.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                warn();
            }

            public void removeUpdate(DocumentEvent e) {
                warn();
            }

            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
                if(reserver==false)
                {
                  if(nomtext.getText()== null ){
                    AfficherReservation();
                }
                  else
                  {    if(nomtext.getText()!= null)
                         {ResultSet res = Gc.Client_Actuel_Filtre(nomtext.getText());
                         Tclient.setModel(new MonModele(res));}
                       
                   }
              /*  }else{ 
               if(cintext.getText()== null){
                        AfficherReservation();  }
                      else{ 
                       {ResultSet res = Gc.Client_Actuel_Filtrecin(cintext.getText());
                         Tclient.setModel(new MonModele(res));}
                        }*/
 
               }} 
            
        });
    }
     
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tclient = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nomtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        Tclient.setBackground(new java.awt.Color(153, 153, 153));
        Tclient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TclientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tclient);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Les réservations des clients actuels");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nom");

        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("si vous voulez consulter le profile d un client particulier clicker sur la ligne qui le concerne!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nomtext, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TclientMouseClicked
       TableModel model = (TableModel)Tclient.getModel();
      String cin=model.getValueAt(Tclient.getSelectedRow(),0).toString();
        new JFProfil(cin).setVisible(true);
     
    }//GEN-LAST:event_TclientMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tclient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomtext;
    // End of variables declaration//GEN-END:variables
}
