/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing.Client;

/**
 *
 * @author amine
 */
public class JpAccueil extends javax.swing.JPanel {

    IHMClient Jp ;
    /**
     * Creates new form JpClient
     */
    public JpAccueil() {
        initComponents();
    }
    
    public JpAccueil(IHMClient Jp)
    {
        initComponents();
        this.Jp = Jp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 329));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(210, 180, 140));
        jLabel6.setText("L'hôtel propose des chambres et des suites lumineuses. Elles possèdent tous les équipements nécessaires pour que vous passiez un ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(210, 180, 140));
        jLabel5.setText("Nos prestations répondent parfaitement aux attentes d'une clientèle exigeante. ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 180, 140));
        jLabel1.setText("Situé en plein centre-ville, à seulement 20 mètres des plages de sable fin, à 500 mètres de la gare et à 6 kilomètres de l'aéroport, ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(210, 180, 140));
        jLabel3.setText(" notre hôtel est le cadre idéal pour profiter du charme de Tanger, ville dynamique en pleine croissance. Notre établissement de  ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(210, 180, 140));
        jLabel4.setText("4 étoiles de style contemporain et confortable vous accueille avec l'hospitalité ancestrale marocaine.");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(210, 180, 140));
        jLabel7.setText(" et internationales. Vous savourerez un bon repas avant de prendre un verre dans l'atmosphère détendue du bar-jardin de l'hôtel");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(210, 180, 140));
        jLabel8.setText(" ou divertirez dans la discothèque de l'hôtel. ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 329));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(210, 180, 140));
        jLabel10.setText("L'hôtel propose des chambres et des suites lumineuses. Elles possèdent tous les équipements nécessaires pour que vous passiez un ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(210, 180, 140));
        jLabel11.setText("Nos prestations répondent parfaitement aux attentes d'une clientèle exigeante. ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(210, 180, 140));
        jLabel2.setText("Situé en plein centre-ville, à seulement 20 mètres des plages de sable fin, à 500 mètres de la gare et à 6 kilomètres de l'aéroport, ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(210, 180, 140));
        jLabel12.setText(" notre hôtel est le cadre idéal pour profiter du charme de Tanger, ville dynamique en pleine croissance. Notre établissement de  ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(210, 180, 140));
        jLabel13.setText("4 étoiles de style contemporain et confortable vous accueille avec l'hospitalité ancestrale marocaine.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(210, 180, 140));
        jLabel14.setText(" et internationales. Vous savourerez un bon repas avant de prendre un verre dans l'atmosphère détendue du bar-jardin de l'hôtel");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(210, 180, 140));
        jLabel15.setText(" ou divertirez dans la discothèque de l'hôtel. ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(210, 180, 140));
        jLabel16.setText("séjour relaxant. Pour vous restaurer, l'hôtel met à votre disposition des restaurants servants des spécialités espagnoles, marocaines ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        lblBackground.setBackground(new java.awt.Color(255, 51, 51));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundClient.jpg"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(210, 180, 140));
        jLabel9.setText("séjour relaxant. Pour vous restaurer, l'hôtel met à votre disposition des restaurants servants des spécialités espagnoles, marocaines ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
