/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing.Client;

import Metiers.GestionPlaintes;
import javax.swing.JOptionPane;

/**
 *
 * @author amine
 */
public class JpPlaintes extends javax.swing.JPanel {

    GestionPlaintes Gp = new GestionPlaintes();
    IHMClient Jp;
    /**
     * Creates new form NewJPanel
     */
    public JpPlaintes() {
        initComponents();
    }

    public JpPlaintes(IHMClient Jp)
    {
        initComponents();
        this.Jp = Jp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblRemerciement = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(210, 180, 140));
        jLabel3.setText("Soumettre");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        txtDescription.setBackground(new java.awt.Color(29, 110, 175));
        txtDescription.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });
        add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 260, 80));

        lblRemerciement.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblRemerciement.setText("Votre remarque sera prix en consideration . On vous souhaite un bon séjour !!");
        add(lblRemerciement, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(210, 180, 140));
        jLabel2.setText("Entrez Votre Plainte");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundClient.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 329));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 329));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        String desc = txtDescription.getText();
        Gp.Ajouter_Plainte(Jp.cin, desc);
        lblRemerciement.setText("Votre remarque sera prise en consideration . On vous souhaite un bon séjour !!");
        txtDescription.setText("");
        JOptionPane.showMessageDialog(null, "Plainte Envoyée " , "Merci",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    public void vider()
    {
        txtDescription.setText("");
        lblRemerciement.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblRemerciement;
    private javax.swing.JTextField txtDescription;
    // End of variables declaration//GEN-END:variables
}
