/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing.Client;

import Metiers.GestionDemande;
import Metiers.GestionService;
import Swing.Receptionniste.JPFacture;
import TableModele.MonModele;
import TableModele.MonMondelePanier;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author amine
 */
public class JpServicesold extends javax.swing.JPanel {

    Vector<String> desTotale = new Vector<String>() ;
    Vector<String> desUnique = new Vector<String>() ;
    Vector<String> desPanier = new Vector<String>() ;
    Vector<Integer> quantite = new Vector<Integer>();
    GestionService Gs= new GestionService();
    GestionDemande Gd = new GestionDemande();
    IHMClient Jp;
    int ligneT ;
    int ligneP ;
    
    String titre = "Désignation";
    /**
     * Creates new form JpServices
     */
    public JpServicesold() {
        initComponents();
    }
    
    public JpServicesold(IHMClient Jp)
    {
        initComponents();
        afficherService();
        this.Jp = Jp;
        ligneT = 0;
    }
    
    public void afficherService()
    {
        ResultSet Rs = Gs.ListeServices();
        MonModele modele = new MonModele(Rs);
        Tservice.setModel(modele);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tservice = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TPanier = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnValider = new javax.swing.JButton();
        txtpTotale = new javax.swing.JLabel();
        txtPrix = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 329));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tservice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tservice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TserviceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tservice);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 161));

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));
        jPanel1.setForeground(new java.awt.Color(51, 255, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Liste des services");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 453, -1));

        TPanier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TPanier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPanierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TPanier);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 100, 161));

        jPanel2.setForeground(new java.awt.Color(52, 152, 219));

        jLabel2.setText("Panier");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, 30));

        btnValider.setText("Valider");
        btnValider.setEnabled(false);
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });
        add(btnValider, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        txtpTotale.setForeground(new java.awt.Color(0, 102, 102));
        add(txtpTotale, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 285, -1, -1));
        add(txtPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 285, -1, -1));

        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 329));
    }// </editor-fold>//GEN-END:initComponents

    private void TserviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TserviceMouseClicked
        // TODO add your handling code here:
        int i=0;
        int lig = Tservice.getSelectedRow();
          for( ; i<ligneP && !(Tservice.getValueAt(lig, 2).toString().equalsIgnoreCase(desUnique.get(i))) ; i++);
        if(i>=ligneP)
        {
          desTotale.add(Tservice.getValueAt(lig, 2).toString());
          desUnique.add(Tservice.getValueAt(lig, 2).toString());
          desPanier.add(Tservice.getValueAt(lig, 2).toString());
          quantite.add(1);
          TPanier.setModel(new MonMondelePanier(desPanier,titre));
          ligneT++;
          ligneP++;
        }
        else
        {
           quantite.set(i,quantite.get(i)+1);
           desTotale.add(Tservice.getValueAt(lig, 2).toString());
           ligneT++;
           desPanier.set(i, Tservice.getValueAt(lig, 2).toString()+"   *"+quantite.get(i));
           TPanier.setModel(new MonMondelePanier(desPanier,titre));
        }
      
        float prix =0;
        for (int j=0 ; j<ligneT ; j++)
        {
            ResultSet Res = Gs.Prix_Service(desTotale.get(j));
            try {
                Res.first();
                prix+= Res.getFloat(1);  
            } catch (SQLException ex) {
                Logger.getLogger(JPFacture.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        txtPrix.setText(prix+" Dh");
        txtpTotale.setText("Prix Totale a payer :");
        btnValider.setEnabled(true);
    }//GEN-LAST:event_TserviceMouseClicked

    private void TPanierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPanierMouseClicked
        // TODO add your handling code here:
        int lig = TPanier.getSelectedRow();
        int i=0 ;
        for (; /*i<ligneT && */!(desTotale.get(i).equalsIgnoreCase(desUnique.get(lig))) ; i++);
        desTotale.remove(i);
        ligneT--;
        if(quantite.get(lig)>1)
        {
            
            quantite.set(lig , quantite.get(lig)-1);
            desPanier.set(lig, desUnique.get(lig)+"   *"+quantite.get(lig));
            TPanier.setModel(new MonMondelePanier(desPanier,titre));
            
        }
        else
        {
        desPanier.remove(lig);
        desUnique.remove(lig);
        quantite.remove(lig);
        TPanier.setModel(new MonMondelePanier(desPanier,titre));
        ligneP--;
        }
        
        float prix =0;
        for (int j=0 ; j<ligneT ; j++)
        {
            ResultSet Res = Gs.Prix_Service(desTotale.get(j));
            try {
                Res.first();
                prix+= Res.getFloat(1);  
            } catch (SQLException ex) {
                Logger.getLogger(JPFacture.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        txtPrix.setText(prix+" Dh");
        
        if (ligneT==0)
        {
            btnValider.setEnabled(false);
            txtPrix.setText("");
            txtpTotale.setText("");
        }
        
    }//GEN-LAST:event_TPanierMouseClicked

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        // TODO add your handling code here:
//        for (int i=0 ; i<ligneT ; i++)
//        {
//            System.out.print(desTotale.get(i));
//        }
//        System.out.print("             " +ligneT +"\n");
//        for (int i=0 ; i<ligneP ; i++)
//        {
//            System.out.print(desUnique.get(i));
//        }
//        System.out.print("\n");
//        for (int i=0 ; i<ligneP ; i++)
//        {
//            System.out.print(desPanier.get(i));
//        }
//        System.out.print("             " +ligneP +"\n");
        
        
        for(int i=0 ; i<ligneT ; i++)
        {
            ResultSet Rs = Gs.get_IDS(desTotale.get(i));
            try {
                Rs.first();
                Gd.Add_Demande("50", Rs.getInt(1));
            } catch (SQLException ex) {
                Logger.getLogger(JpServicesold.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Vider();
        JOptionPane.showMessageDialog(null, "Vos Services seront bientot Disponnible !!" , "Merci",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnValiderActionPerformed

    public void ViderTable ()
    {
        MonModele model = new MonModele();
        Tservice.setModel(model);
    }
    
    public void ViderPanier ()
    {
        MonMondelePanier model = new MonMondelePanier();
        TPanier.setModel(model);
    }
    
    public void Vider()
    {
        txtPrix.setText("");
        txtpTotale.setText("");
        ViderPanier();
        ligneT = 0 ;
        ligneP =0 ;
        btnValider.setEnabled(false);
        desTotale.clear();
        desPanier.clear();
        desUnique.clear();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TPanier;
    private javax.swing.JTable Tservice;
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtPrix;
    private javax.swing.JLabel txtpTotale;
    // End of variables declaration//GEN-END:variables
}
