/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing.Client;

import Metiers.GestionDemande;
import Metiers.GestionService;
import Swing.Receptionniste.JPFacture;
import TableModele.MonModele;
import TableModele.MonMondelePanier;
import TableModele.SimpleHeaderRenderer;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author amine
 */
public class JpServices extends javax.swing.JPanel {

    Vector<String> desTotale = new Vector<String>() ;
    Vector<String> desUnique = new Vector<String>() ;
    Vector<String> desPanier = new Vector<String>() ;
    Vector<Integer> quantite = new Vector<Integer>();
    GestionService Gs= new GestionService();
    GestionDemande Gd = new GestionDemande();
    IHMClient Jp;
    int ligneT ;
    int ligneP ;
    
    String titre = "Désignation";
    /**
     * Creates new form NewJPanel
     */
    public JpServices() {
        initComponents();
    }
    
    public JpServices(IHMClient Jp)
    {
        initComponents();
        afficherService();
        this.Jp = Jp;
        ligneT = 0;
        Tservice.getTableHeader().setDefaultRenderer(new SimpleHeaderRenderer());
        TPanier.getTableHeader().setDefaultRenderer(new SimpleHeaderRenderer());
    }
    
    public void afficherService()
    {
        ResultSet Rs = Gs.ListeServices();
        MonModele modele = new MonModele(Rs);
        Tservice.setModel(modele);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblValider = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpTotale = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrix = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TPanier = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tservice = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(210, 180, 140));
        jLabel3.setText("Les Services");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        lblValider.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        lblValider.setForeground(new java.awt.Color(210, 180, 140));
        lblValider.setText("Valider");
        lblValider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblValiderMouseClicked(evt);
            }
        });
        add(lblValider, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(210, 180, 140));
        jLabel4.setText("Panier");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Simple Click  dans le tableau des services pour ajouter dans le panier .");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Simple Click dans le Panier pour annuler le service .");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtpTotale.setFont(new java.awt.Font("Serif", 3, 20)); // NOI18N
        txtpTotale.setForeground(new java.awt.Color(210, 180, 140));
        txtpTotale.setText("Prix Totale a payer :");
        add(txtpTotale, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Vous pouvez ajouter autant de services que vous voulez .");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txtPrix.setFont(new java.awt.Font("Serif", 3, 20)); // NOI18N
        txtPrix.setForeground(new java.awt.Color(210, 180, 140));
        add(txtPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, -1, -1));

        TPanier.setBackground(new java.awt.Color(14, 41, 86));
        TPanier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TPanier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPanierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TPanier);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 150, 150));

        Tservice.setAutoCreateRowSorter(true);
        Tservice.setBackground(new java.awt.Color(14, 41, 86));
        Tservice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tservice.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        Tservice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TserviceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tservice);
        Tservice.getAccessibleContext().setAccessibleName("");

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 360, 150));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundClient.jpg"))); // NOI18N
        lblBackground.setOpaque(true);
        add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TserviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TserviceMouseClicked
        // TODO add your handling code here:
        int i=0;
        int lig = Tservice.getSelectedRow();
          for( ; i<ligneP && !(Tservice.getValueAt(lig, 2).toString().equalsIgnoreCase(desUnique.get(i))) ; i++);
        if(i>=ligneP)
        {
          desTotale.add(Tservice.getValueAt(lig, 2).toString());
          desUnique.add(Tservice.getValueAt(lig, 2).toString());
          desPanier.add(Tservice.getValueAt(lig, 2).toString());
          quantite.add(1);
          TPanier.setModel(new MonMondelePanier(desPanier,titre));
          ligneT++;
          ligneP++;
        }
        else
        {
           quantite.set(i,quantite.get(i)+1);
           desTotale.add(Tservice.getValueAt(lig, 2).toString());
           ligneT++;
           desPanier.set(i, Tservice.getValueAt(lig, 2).toString()+"   *"+quantite.get(i));
           TPanier.setModel(new MonMondelePanier(desPanier,titre));
        }
      
        float prix =0;
        for (int j=0 ; j<ligneT ; j++)
        {
            ResultSet Res = Gs.Prix_Service(desTotale.get(j));
            try {
                Res.first();
                prix+= Res.getFloat(1);  
            } catch (SQLException ex) {
                Logger.getLogger(JPFacture.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        txtPrix.setText(prix+" Dh");
        txtpTotale.setText("Prix Totale a payer :");
    }//GEN-LAST:event_TserviceMouseClicked

    private void TPanierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPanierMouseClicked
        // TODO add your handling code here:
        int lig = TPanier.getSelectedRow();
        int i=0 ;
        for (; /*i<ligneT && */!(desTotale.get(i).equalsIgnoreCase(desUnique.get(lig))) ; i++);
        desTotale.remove(i);
        ligneT--;
        if(quantite.get(lig)>1)
        {
            
            quantite.set(lig , quantite.get(lig)-1);
            desPanier.set(lig, desUnique.get(lig)+"   *"+quantite.get(lig));
            TPanier.setModel(new MonMondelePanier(desPanier,titre));
            
        }
        else
        {
        desPanier.remove(lig);
        desUnique.remove(lig);
        quantite.remove(lig);
        TPanier.setModel(new MonMondelePanier(desPanier,titre));
        ligneP--;
        }
        
        float prix =0;
        for (int j=0 ; j<ligneT ; j++)
        {
            ResultSet Res = Gs.Prix_Service(desTotale.get(j));
            try {
                Res.first();
                prix+= Res.getFloat(1);  
            } catch (SQLException ex) {
                Logger.getLogger(JPFacture.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        txtPrix.setText(prix+" Dh");
        
        if (ligneT==0)
        {
            txtPrix.setText("");
            txtpTotale.setText("");
        }
    }//GEN-LAST:event_TPanierMouseClicked

    private void lblValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblValiderMouseClicked
        // TODO add your handling code here:
        if(ligneP==0)
        {
            JOptionPane.showMessageDialog(null, "Pannier Vide !!" , "Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
        else    
        {
        for(int i=0 ; i<ligneT ; i++)
        {
            ResultSet Rs = Gs.get_IDS(desTotale.get(i));
            try {
                Rs.first();
                Gd.Add_Demande(Jp.cin, Rs.getInt(1));
            } catch (SQLException ex) {
                Logger.getLogger(JpServicesold.class.getName()).log(Level.SEVERE, null, ex);   
        }
        }
         JOptionPane.showMessageDialog(null, "Vos Services seront bientot Disponnible !!" , "Merci",JOptionPane.INFORMATION_MESSAGE);
        }
        Vider();
    }//GEN-LAST:event_lblValiderMouseClicked


    public void ViderTable ()
    {
        MonModele model = new MonModele();
        Tservice.setModel(model);
    }
    
    public void ViderPanier ()
    {
        MonMondelePanier model = new MonMondelePanier();
        TPanier.setModel(model);
    }
    
    public void Vider()
    {
        txtPrix.setText("");
        txtpTotale.setText("");
        ViderPanier();
        ligneT = 0 ;
        ligneP =0 ;
        desTotale.clear();
        desPanier.clear();
        desUnique.clear();
        quantite.clear();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TPanier;
    private javax.swing.JTable Tservice;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblValider;
    private javax.swing.JLabel txtPrix;
    private javax.swing.JLabel txtpTotale;
    // End of variables declaration//GEN-END:variables
}
