/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing.Receptionniste;

import Metiers.GestionClients;
import TableModele.MonModele;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author amine
 */
public class JPClients extends javax.swing.JPanel {

    GestionClients Gc = new GestionClients();
    IHMReceptionniste Jp;

    /**
     * Creates new form JPClients
     */
    public JPClients() {
        initComponents();
    }
    
   public JPClients(IHMReceptionniste Jp)
   {
       this.Jp = Jp; 
       initComponents();
       AfficherAllClient();
       FiltrerNom();
       
   }
   
   public void AfficherAllClient()
    {
        L1.setText("Tout Les Clients :");
        ResultSet Res = Gc.ALL_Clients();
        MonModele modele = new MonModele(Res);
        TClients.setModel(modele);
    }
   
   public void AfficherReservation()
    {
        L1.setText("Clients Ayant une Reservation :");
        ResultSet Res = Gc.Client_Actuel();
        MonModele modele = new MonModele(Res);
        TClients.setModel(modele);
    }
   
   public void FiltrerNom()
    {
        txtRechercher.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                warn();
            }

            public void removeUpdate(DocumentEvent e) {
                warn();
            }

            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
              if(boxRecherche.getSelectedItem()=="Nom")
              {
                  if(RadioReserver.isSelected()==false)
                  {
                      if(txtRechercher.getText()== null)
                      {
                          AfficherAllClient();
                      }
                      else 
                      {   
                          ResultSet res = Gc.FiltrerNom(txtRechercher.getText());
                          TClients.setModel(new MonModele(res));
                      } 
                  }
                  else
                  {
                      if(txtRechercher.getText()== null)
                      {
                          AfficherReservation();
                      }
                      else
                      {   
                          ResultSet res = Gc.Client_Actuel_Filtrer_Nom(txtRechercher.getText());
                          TClients.setModel(new MonModele(res));
                      }
                  }
              }
              else
              {
                  if(RadioReserver.isSelected()==false)
                  {
                      if(txtRechercher.getText()== null)
                      {
                          AfficherAllClient();
                      }
                      else
                      {   
                          ResultSet res = Gc.FiltrerCin(txtRechercher.getText());
                          TClients.setModel(new MonModele(res));
                      } 
                  }  
                  else
                  {
                      if(txtRechercher.getText()== null)
                      {
                          AfficherReservation();
                      }
                      else
                      {   
                          ResultSet res = Gc.Client_Actuel_Filtrer_Cin(txtRechercher.getText());
                          TClients.setModel(new MonModele(res));
                      }
                  }
              }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TClients = new javax.swing.JTable();
        txtRechercher = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSupprimer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RadioReserver = new javax.swing.JRadioButton();
        L1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boxRecherche = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(857, 638));

        TClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TClients);

        txtRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRechercherActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/active-search-2-64x64 (2).png"))); // NOI18N

        jLabel2.setText("Selectionner un Client avec un double Click pour le Afficher / Modifier !");

        btnSupprimer.setText("Supprimer");
        btnSupprimer.setEnabled(false);
        btnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerMouseClicked(evt);
            }
        });
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        jLabel3.setText("Simple Click pour activer la Suppression !");

        RadioReserver.setText("Client Actuel");
        RadioReserver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioReserverMouseClicked(evt);
            }
        });
        RadioReserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioReserverActionPerformed(evt);
            }
        });

        L1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        L1.setText("Tout Les Clients :");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Remarque !! ====> Boutton Decocher : ");

        boxRecherche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cin", "Nom" }));
        boxRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSupprimer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(RadioReserver)
                        .addGap(104, 104, 104)
                        .addComponent(L1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boxRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(boxRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(L1))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(RadioReserver)
                        .addGap(2, 2, 2)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSupprimer)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRechercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercherActionPerformed

    private void TClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TClientsMouseClicked
        if (RadioReserver.isSelected() == false )
        {
        if (evt.getClickCount() == 2) {
            int lig = TClients.getSelectedRow();
            new JFModifierClients(Jp,TClients.getValueAt(lig, 0).toString()).setVisible(true);
            txtRechercher.setText("");
        }  
        else
        {
            btnSupprimer.setEnabled(true);
        }
        }
        
    }//GEN-LAST:event_TClientsMouseClicked

    private void btnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMouseClicked
        // TODO add your handling code here:
        
        

        
    }//GEN-LAST:event_btnSupprimerMouseClicked

    private void RadioReserverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioReserverMouseClicked
        // TODO add your handling code here:
        if (RadioReserver.isSelected())
        {
            AfficherReservation();
            btnSupprimer.setEnabled(false);
            txtRechercher.setText("");
        }
        else
        {
            AfficherAllClient();
            txtRechercher.setText("");   
        }
    }//GEN-LAST:event_RadioReserverMouseClicked

    private void RadioReserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioReserverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioReserverActionPerformed

    private void boxRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRechercheActionPerformed
        // TODO add your handling code here:
        txtRechercher.setText("");
    }//GEN-LAST:event_boxRechercheActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        int reponse =JOptionPane.showConfirmDialog(null, "Etes vous sur de vouloir Supprimer le Client !!", "Suppression !!!", JOptionPane.YES_NO_OPTION);
        if(reponse==JOptionPane.YES_OPTION)
        {
            int lig = TClients.getSelectedRow();
            Gc.delete_client(TClients.getValueAt(lig, 2).toString());
            AfficherAllClient();
            txtRechercher.setText("");
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    
    public void Vider()
    {
        txtRechercher.setText("");
        btnSupprimer.setEnabled(false);
        RadioReserver.setSelected(false);
        btnSupprimer.setEnabled(false);
        boxRecherche.setSelectedIndex(0);
        AfficherAllClient();
    }
    public javax.swing.JTextField gettextRechercher()
    {
        return txtRechercher ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JRadioButton RadioReserver;
    private javax.swing.JTable TClients;
    private javax.swing.JComboBox<String> boxRecherche;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtRechercher;
    // End of variables declaration//GEN-END:variables
}
