/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing.Receptionniste;

import Metiers.GestionClients;
import Metiers.GestionReservation;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Image;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author amine
 */
public class JPRecu extends javax.swing.JPanel {

    GestionClients Gc = new GestionClients();
    GestionReservation Gr= new GestionReservation();
    IHMReceptionniste Jp;
    JPReserver JPr ;
    java.util.Date db , df ;
    String cin , password , login ,idr ;
    int numch ;
    Object[] options1 = {"Dossiers Des Recu",
                     "PDF Recu",
                     "Retour"};
    
    /**
     * Creates new form JPRecu
     */
    public JPRecu() {
        initComponents();
    }
    
    public JPRecu(IHMReceptionniste Jp)
    {
        this.Jp=Jp ;
        initComponents();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Retour = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelRecu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(857, 603));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 210, 73));
        jLabel1.setText("Reservation Ajoutée avec Succées !!!");

        Retour.setText("Reserver");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setText("Veuiller Telecharger Le Recu : ");

        labelRecu.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        labelRecu.setText("Cliquer ici !!");
        labelRecu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRecu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRecuMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pouce_logo.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setText("Voulez_vous ajouter une nouvelle reservation ?");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warning logo.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warning logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(Retour))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelRecu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(labelRecu))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Retour))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        // TODO add your handling code here:
        Jp.JPLReserver.vider();
        Jp.JPLReserver.setVisible(true);
        this.setVisible(false);      
        labelRecu.setText("Cliquer ici !!");
    }//GEN-LAST:event_RetourActionPerformed

    private void labelRecuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRecuMouseClicked
                                                  
                // TODO add your handling code here:
        Generate_pdf();
        int reponse =JOptionPane.showOptionDialog(null, "Selectionnez un choix pour l'ouvrir !!", "Ouverture!!!", JOptionPane.YES_NO_CANCEL_OPTION , JOptionPane.PLAIN_MESSAGE,null,options1,null);
        if(reponse==JOptionPane.YES_OPTION)
        {
            try {
                    Desktop.getDesktop().open((new File("C:\\Users\\omar\\Desktop\\Java Projet 20\\Gestion_Hotel_2019\\Recu")));
            } catch (IOException ex) {
                Logger.getLogger(JPRecu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(reponse==JOptionPane.NO_OPTION)
        {
            try {
                Desktop.getDesktop().open((new File("C:\\Users\\omar\\Desktop\\Java Projet 20\\Gestion_Hotel_2019\\Recu\\recu_"+idr+".pdf")));
            } catch (IOException ex) {
                Logger.getLogger(JPRecu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
    }//GEN-LAST:event_labelRecuMouseClicked

    public void Generate_pdf ()
    {
        try { 
                String dated = db.toString();
                String datef = df.toString();
                String chambre=""+numch;

                ResultSet Res= Gr.getIDR(cin, numch, db, df);
                try {
                    Res.next();
                    int IDR = Res.getInt("ID_R");
                    idr=""+IDR;
                    labelRecu.setText("recu_"+idr+".pdf");
                } catch (SQLException ex) {
                    Logger.getLogger(JPRecu.class.getName()).log(Level.SEVERE, null, ex);
                }
                Res = Gc.RechercherCLient(cin);
                Res.next();
                String nom = Res.getString("nom");
                String prenom = Res.getString("prenom");
                java.util.Date DateN = Res.getDate("datenaissance");
                String DateNaissance = DateN.toString();
                Calendar cal=Calendar.getInstance();
                int month = cal.get(Calendar.MONTH);
                int year = cal.get(Calendar.YEAR);
                int day = cal.get(Calendar.DAY_OF_MONTH);
                month++ ;
                String annee = ""+year;
                String jour = ""+day ;
                String mois = ""+month;
                
                
                Document document = new Document() ;
                try {
                    try {
                        PdfWriter.getInstance(document, new FileOutputStream("C:\\Users\\omar\\Desktop\\Java Projet 20\\Gestion_Hotel_2019\\recu\\recu_"+idr+".pdf"));
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(JPRecu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    
                    document.open();
                    Image image = Image.getInstance("logo1.png");
                    document.add(image);
                    Paragraph p = new Paragraph("Recu                                                "+jour+"/"+mois+"/"+annee,FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD,BaseColor.MAGENTA));
                    document.add(p);
                    document.add(new Paragraph("***************************************************************************************************"));
                    document.add(new Paragraph("\n"));
                    document.add(new Paragraph("\n"));
                    
                    
                    PdfPTable table = new PdfPTable(2);
                    PdfPCell cell = new PdfPCell(new Paragraph("Hotel Hancock",FontFactory.getFont(FontFactory.TIMES_BOLD,15,Font.BOLD,BaseColor.WHITE)));
                    cell.setColspan(4);
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cell.setBackgroundColor(BaseColor.DARK_GRAY);
                    table.addCell(cell);
                    table.addCell("ID Reservation");
                    table.addCell(idr);
                    table.addCell("Cin");
                    table.addCell(cin);
                    table.addCell("Numero de Chambre");
                    table.addCell(chambre);
                    table.addCell("Nom");
                    table.addCell(nom);
                    table.addCell("Prenom");
                    table.addCell(prenom);
                    table.addCell("Date de Debut");
                    table.addCell(dated);
                    table.addCell("Date de fin");
                    table.addCell(datef);
                    table.addCell("Nom de Compte");
                    table.addCell(login);
                    table.addCell("Mot de Passe");
                    table.addCell(password);
                    document.add(table);
                    
                    
                    document.add(new Paragraph("\n"));
                    document.add(new Paragraph("\n"));
                    document.add(new Paragraph("Ne partager jamais votre (Mot de passe / Login) avec personne  !!!",FontFactory.getFont(FontFactory.TIMES_BOLD,14,Font.BOLD,BaseColor.RED)));
                    document.close();
                    
                    
                } catch (DocumentException ex) {
                    Logger.getLogger(JPRecu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(JPRecu.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(JPRecu.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Retour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelRecu;
    // End of variables declaration//GEN-END:variables
}
