/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing.Directeur;

import TableModele.MonModele;
import Metiers.*;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author omar
 */
public class JPersonnel extends javax.swing.JPanel {
   
    IHMDirecteur jdir;
    /**
     * Creates new form Personnel
     */
    public JPersonnel() {
        initComponents();
        refresh();
    }
    public void refresh()
    {
        ResultSet rs=jdir.dr.gp.getAllEmployeactif();
       
        this.tableemploye.setModel(new MonModele(rs));
       
  
        
       this.tableemploye.setSelectionBackground(Color.BLACK);
       this.tableemploye.setSelectionForeground(Color.WHITE);
       this.tableemploye.getTableHeader().setForeground(Color.BLACK);
       this.cbempactuel.setSelected(true);
       
    }
    JPersonnel(IHMDirecteur jdir) {
       this.jdir=jdir;
        initComponents();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableemploye = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnmajc = new javax.swing.JButton();
        btnmajp = new javax.swing.JButton();
        cbempprecedents = new javax.swing.JCheckBox();
        cbempactuel = new javax.swing.JCheckBox();
        txtchercher = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btncherche = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtcin = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtsalaire = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbcontrat = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxsexe = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jdatenaissance = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtdescription = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnajouter = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtadresse = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbrole = new javax.swing.JComboBox<>();
        jdatedebut = new com.toedter.calendar.JDateChooser();
        txttelephone = new javax.swing.JTextField();
        jdatefin = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtrole = new javax.swing.JTextField();
        btnresetajout = new javax.swing.JButton();
        txtcodepostal = new javax.swing.JTextField();

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableemploye.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableemploye.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tableemploye.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableemploye.setSurrendersFocusOnKeystroke(true);
        tableemploye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableemployeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableemploye);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 565, 262));

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        jLabel16.setText("Listes des employes");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 159, 41));

        jLabel17.setText("Remarque  : selectionner  un employes pour effectuer l'une de ses operations ");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        btnmajc.setText("Afficher/Modifier le contrat");
        btnmajc.setEnabled(false);
        btnmajc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmajcActionPerformed(evt);
            }
        });
        jPanel4.add(btnmajc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 187, -1));

        btnmajp.setText("Afficher/Modifier les informations personnel");
        btnmajp.setEnabled(false);
        btnmajp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmajpActionPerformed(evt);
            }
        });
        jPanel4.add(btnmajp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        cbempprecedents.setText("Afficher  les employes precedents ");
        cbempprecedents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbempprecedentsActionPerformed(evt);
            }
        });
        jPanel4.add(cbempprecedents, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

        cbempactuel.setText("Afficher employes actuel ");
        cbempactuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbempactuelActionPerformed(evt);
            }
        });
        jPanel4.add(cbempactuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        txtchercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchercherActionPerformed(evt);
            }
        });
        jPanel4.add(txtchercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 172, -1));

        jLabel18.setText("                Chercher  :");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        btncherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/active-search-2-64x64 (2).png"))); // NOI18N
        btncherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnchercheMouseClicked(evt);
            }
        });
        btncherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchercheActionPerformed(evt);
            }
        });
        jPanel4.add(btncherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 36, 25));

        jLabel19.setText("la recherche se fait par le nom ou le cin ou bien le role");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 302, -1));

        jTabbedPane1.addTab("Contrats/informations des employes", jPanel4);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcinActionPerformed(evt);
            }
        });
        jPanel2.add(txtcin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 206, -1));
        jPanel2.add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 206, -1));
        jPanel2.add(txtsalaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 193, -1));
        jPanel2.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 206, -1));
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 206, -1));

        jLabel1.setText("CIN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 22));

        cbcontrat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CDD", "CDI", "CTT" }));
        cbcontrat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbcontratItemStateChanged(evt);
            }
        });
        cbcontrat.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbcontratPropertyChange(evt);
            }
        });
        jPanel2.add(cbcontrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 193, -1));

        jLabel2.setText("Nom");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 36, 22));

        cbxsexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));
        jPanel2.add(cbxsexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 206, -1));

        jLabel3.setText("Prenom");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 54, 22));

        jLabel13.setText("Type Contrat");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));
        jPanel2.add(jdatenaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 206, -1));

        jLabel4.setText("Email");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        txtdescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescriptionActionPerformed(evt);
            }
        });
        jPanel2.add(txtdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 193, 59));

        jLabel5.setText("Date Naissance ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        btnajouter.setText("Ajouter ");
        btnajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajouterMouseClicked(evt);
            }
        });
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });
        jPanel2.add(btnajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 208, -1));

        jLabel6.setText("Sexe");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel7.setText("Telephone");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));
        jPanel2.add(txtadresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 206, -1));

        jLabel14.setText("Description");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        cbrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerant", "Receptionniste", "autres" }));
        cbrole.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbroleItemStateChanged(evt);
            }
        });
        jPanel2.add(cbrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 200, -1));
        jPanel2.add(jdatedebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 200, -1));
        jPanel2.add(txttelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 206, -1));
        jPanel2.add(jdatefin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 200, -1));

        jLabel8.setText("Adresse");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel9.setText("Date fin");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jLabel10.setText("Date debut");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel11.setText("Role ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 50, 20));

        jLabel12.setText("Salaire");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 60, 20));

        jLabel15.setText("code postal");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        txtrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroleActionPerformed(evt);
            }
        });
        jPanel2.add(txtrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 193, -1));

        btnresetajout.setText(" Réinitialiser");
        btnresetajout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnresetajoutMouseClicked(evt);
            }
        });
        jPanel2.add(btnresetajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 179, -1));

        txtcodepostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodepostalActionPerformed(evt);
            }
        });
        jPanel2.add(txtcodepostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 200, -1));

        jTabbedPane1.addTab("Ajouter Employé", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnchercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchercheActionPerformed

    private void btnchercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnchercheMouseClicked
        String info = this.txtchercher.getText();
        ResultSet rs=this.jdir.dr.gp.getEmployeByInfos(info);
        this.tableemploye.setModel(new MonModele(rs));
    }//GEN-LAST:event_btnchercheMouseClicked

    private void txtchercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtchercherActionPerformed

    private void cbempactuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbempactuelActionPerformed

        choixtable();

        // TODO add your handling code here:
    }//GEN-LAST:event_cbempactuelActionPerformed

    private void cbempprecedentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbempprecedentsActionPerformed
        choixtable();
    }//GEN-LAST:event_cbempprecedentsActionPerformed

    private void btnmajpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmajpActionPerformed

        String cinD=this.jdir.dr.getCinE();
        int lig=this.tableemploye.getSelectedRow();
        String cinP=this.tableemploye.getValueAt(lig,0).toString();
        String role=this.tableemploye.getValueAt(lig, 1).toString();
        JmajPersonnel jmp;
      
        try {
            jmp = new JmajPersonnel(cinD,cinP,role,jdir.dr,this);
            jmp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(JPersonnel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnmajpActionPerformed

    private void btnmajcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmajcActionPerformed

        String cinD=this.jdir.dr.getCinE();
        int lig=this.tableemploye.getSelectedRow();
        String cinP=this.tableemploye.getValueAt(lig,0).toString();
        String role=this.tableemploye.getValueAt(lig, 1).toString();
        String nom=this.tableemploye.getValueAt(lig,2).toString();
        String prenom=this.tableemploye.getValueAt(lig,3).toString();
        JMajcontrat jmc =new JMajcontrat(cinP,nom,prenom,this.jdir.dr,this);
        jmc.setVisible(true);
    }//GEN-LAST:event_btnmajcActionPerformed

    private void tableemployeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableemployeMouseClicked
        this.btnmajc.setEnabled(true);
        this.btnmajp.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_tableemployeMouseClicked
   
    private void txtroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroleActionPerformed

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed

        String cin=this.txtcin.getText();
          if(cin.length()>11)
         {
             JOptionPane.showMessageDialog(null, " CIN est invalide !!");
             txtcin.setText("");
               return; 
             
         }
        String nom =this.txtnom.getText();
        String prenom=this.txtprenom.getText();
        String telephone = this.txttelephone.getText();
        String email=this.txtemail.getText();
        
        Date datenaissance = this.jdatenaissance.getDate();
        Calendar cal1 = Calendar.getInstance();
           
      
            cal1.set(Calendar.YEAR+1900-18, 1, 1);
          
            Date DateNaissanceMini=new java.sql.Date(cal1.getTime().getTime());
         if(datenaissance.after(DateNaissanceMini))
        {
           
              JOptionPane.showMessageDialog(null, "Date naissance invalide!!");
              return;
        }
        String Sexe=this.cbxsexe.getSelectedItem().toString();
        String adresse=this.txtadresse.getText();
        int codepostal=Integer.parseInt(this.txtcodepostal.getText());
        

        /* contrat */
        Date datedebut=this.jdatedebut.getDate();
        Date datefin=this.jdatefin.getDate();
        Date date= new java.sql.Date(Calendar.getInstance().getTime().getTime());
         String role=this.txtrole.getText();
        float salaire=Float.parseFloat(this.txtsalaire.getText());
        String typec=this.cbcontrat.getSelectedItem().toString();
        String description = this.txtdescription.getText();
        String login = cin+"_"+prenom;
 
         int temp =(int)( Math.random()*( 999999 - 100000 + 1 ) ) + 100000;
         String password = ""+temp  ;
         
         if(this.jdir.dr.gp.CheckCinPersonnel(cin))
          {
               JOptionPane.showMessageDialog(null, "un employe possedant ce CIN existe deja !!");
               return; 
          }
         int reponse =JOptionPane.showConfirmDialog(null, "Etes vous sur du vouloir ajouter ses Employer", "Fermeture !!!", JOptionPane.YES_NO_OPTION);
         if(reponse==JOptionPane.NO_OPTION)
        {
            return;
        }
          
        if(typec.equalsIgnoreCase("CDI"))
        {
            Calendar cal = Calendar.getInstance();
           
      
            cal.set(2099, 1, 1);
          
            datefin=new java.sql.Date(cal.getTime().getTime());
             
        }
        if(datefin.before(datedebut) || datedebut.before(date) ){

            JOptionPane.showMessageDialog(null, " la date fin ou la date debut non valide ");
            return ;

        }

        if(role.equalsIgnoreCase("gerant"))
        {
            this.jdir.dr.gp.ajouterGerant(cin, nom, prenom, datenaissance, email, telephone, Sexe, adresse,codepostal);
            this.jdir.dr.gcp.ajouter_Compte(login, cin, password, role);

        }
        else if(role.equalsIgnoreCase("receptionniste"))
        {
            this.jdir.dr.gp.ajouterReceptioniste(cin, nom, prenom, datenaissance, email, telephone, Sexe, adresse, codepostal);
            this.jdir.dr.gcp.ajouter_Compte(login, cin, password, role);

        }
        else if(role.equalsIgnoreCase("autres"))
        {
            this.jdir.dr.gp.ajouterEmploye(cin, nom, prenom, datenaissance, email, telephone, Sexe, adresse, codepostal);
            this.jdir.dr.gcp.ajouter_Compte(login, cin, password, role);
            this.jdir.dr.gcp.Desactiver_Compte(cin);

        }

        this.jdir.dr.gc.AjouteContrat(cin, this.jdir.dr.getCinE(), datefin, datedebut, typec, role, salaire, description);
        JOptionPane.showMessageDialog(null, "Personnel Ajoutée !!");
        vider();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnajouterActionPerformed

    private void txtdescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescriptionActionPerformed

    private void cbcontratPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbcontratPropertyChange

        // TODO add your handling code here:
    }//GEN-LAST:event_cbcontratPropertyChange

    private void cbcontratItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbcontratItemStateChanged
        // TODO add your handling code here:
        if(this.cbcontrat.getSelectedItem().toString().equalsIgnoreCase("CDI"))
        {
            this.jdatefin.setEnabled(false);
        }
        else
        {
            this.jdatefin.setEnabled(true);

        }
    }//GEN-LAST:event_cbcontratItemStateChanged
    public void  vider()
    {
        this.txtcin.setText("");
        this.txtadresse.setText("");
        this.txtcodepostal.setText("");
        this.txtdescription.setText("");
        this.txtemail.setText("");
        this.txtnom.setText("");
        this.txtrole.setText("Gerant");
        this.txtprenom.setText("");
        this.txttelephone.setText("");
        this.txtsalaire.setText("");
        this.jdatenaissance.setDate(null);
        this.jdatedebut.setDate(null);
        this.jdatefin.setDate(null);
        this.cbcontrat.setSelectedIndex(0);
        this.cbrole.setSelectedIndex(0); 
        this.cbxsexe.setSelectedIndex(0); 
    }
    private void txtcinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcinActionPerformed

    }//GEN-LAST:event_txtcinActionPerformed

    private void btnresetajoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresetajoutMouseClicked
        vider();
    }//GEN-LAST:event_btnresetajoutMouseClicked

    private void cbroleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbroleItemStateChanged
         
        if(this.cbrole.getSelectedItem().toString().equalsIgnoreCase("autres"))
        {
            this.txtrole.setEnabled(true);
            this.txtrole.setText("");
        }
        else
        {
            this.txtrole.setEnabled(false);
            txtrole.setText(cbrole.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbroleItemStateChanged

    private void btnajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajouterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnajouterMouseClicked

    private void txtcodepostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodepostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodepostalActionPerformed
   /**
    * cette fonction permet d'afficher les employes dans le tableau
    * selon le choix de l'utilisateur 
    */
    public void  choixtable()
    {
          if(this.cbempprecedents.isSelected() && this.cbempactuel.isSelected()) 
        {
          ResultSet rs =this.jdir.dr.gp.getAllEmploye();
           this.tableemploye.setModel(new MonModele(rs));
        }
        
        else if( this.cbempprecedents.isSelected() && !this.cbempactuel.isSelected())
        {
            ResultSet rs =this.jdir.dr.gp.getAllEmployeprecedents();
           this.tableemploye.setModel(new MonModele(rs));
            
        }
        else if(this.cbempactuel.isSelected() &&  !this.cbempprecedents.isSelected()  )
        { 
            ResultSet rs =this.jdir.dr.gp.getAllEmployeactuels();
            this.tableemploye.setModel(new MonModele(rs));
        }
        else  
        {
            ResultSet rs =this.jdir.dr.gp.getAllEmployeactuels();
            this.tableemploye.setModel(new MonModele(rs));
            this.cbempactuel.setSelected(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btncherche;
    private javax.swing.JButton btnmajc;
    private javax.swing.JButton btnmajp;
    private javax.swing.JButton btnresetajout;
    private javax.swing.JComboBox<String> cbcontrat;
    private javax.swing.JCheckBox cbempactuel;
    private javax.swing.JCheckBox cbempprecedents;
    private javax.swing.JComboBox<String> cbrole;
    private javax.swing.JComboBox<String> cbxsexe;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdatedebut;
    private com.toedter.calendar.JDateChooser jdatefin;
    private com.toedter.calendar.JDateChooser jdatenaissance;
    private javax.swing.JTable tableemploye;
    private javax.swing.JTextField txtadresse;
    private javax.swing.JTextField txtchercher;
    private javax.swing.JTextField txtcin;
    private javax.swing.JTextField txtcodepostal;
    private javax.swing.JTextField txtdescription;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrole;
    private javax.swing.JTextField txtsalaire;
    private javax.swing.JTextField txttelephone;
    // End of variables declaration//GEN-END:variables
}
